/** Código do Custom Pixel da Shopify que alimenta o live view. Colar em Configurações > Eventos do cliente > Adicionar pixel personalizado. */
export function pixelSnippet(origin: string, slug: string, key: string): string {
  const url = `${origin}/api/track/${slug}?k=${key}`
  return [
    '// Grupo Don — live view da loja',
    `const ENDPOINT = '${url}';`,
    'const HEARTBEAT_MS = 20000;',
    'let sid = null, path = "/", source = null, fresh = false, timer = null;',
    '',
    'const rand = () => Math.random().toString(36).slice(2) + Date.now().toString(36);',
    'const num = (v) => { const n = Number(v); return isFinite(n) ? n : null; };',
    '',
    'async function ensureSession(href, referrer) {',
    '  try { sid = await browser.sessionStorage.getItem("don_sid"); source = await browser.sessionStorage.getItem("don_src"); } catch (e) {}',
    '  if (!sid) {',
    '    sid = rand(); fresh = true;',
    '    let src = "Direto";',
    '    try {',
    '      const u = new URL(href);',
    '      src = u.searchParams.get("utm_source") || (referrer ? new URL(referrer).hostname.replace(/^www\\./, "") : "Direto");',
    '    } catch (e) {}',
    '    source = src;',
    '    try { await browser.sessionStorage.setItem("don_sid", sid); await browser.sessionStorage.setItem("don_src", source); } catch (e) {}',
    '  }',
    '}',
    '',
    'function send(type, extra) {',
    '  if (!sid) return;',
    '  const body = Object.assign({ sid: sid, type: type, path: path, source: source }, extra || {});',
    '  fetch(ENDPOINT, { method: "POST", keepalive: true, headers: { "Content-Type": "text/plain" }, body: JSON.stringify(body) }).catch(() => {});',
    '}',
    '',
    'analytics.subscribe("page_viewed", async (e) => {',
    '  const loc = (e.context && e.context.document && e.context.document.location) || {};',
    '  path = loc.pathname || "/";',
    '  await ensureSession(loc.href || "", e.context && e.context.document && e.context.document.referrer);',
    '  send(fresh ? "visit" : "ping"); fresh = false;',
    '  if (!timer) timer = setInterval(() => send("ping"), HEARTBEAT_MS);',
    '});',
    '',
    'analytics.subscribe("product_viewed", (e) => {',
    '  const v = e.data && e.data.productVariant;',
    '  send("product", { product: v && v.product && v.product.title, value: num(v && v.price && v.price.amount) });',
    '});',
    '',
    'analytics.subscribe("product_added_to_cart", (e) => {',
    '  const l = e.data && e.data.cartLine;',
    '  send("cart", { product: l && l.merchandise && l.merchandise.product && l.merchandise.product.title, value: num(l && l.cost && l.cost.totalAmount && l.cost.totalAmount.amount) });',
    '});',
    '',
    'const firstItem = (c) => (c && c.lineItems && c.lineItems[0] && c.lineItems[0].title) || null;',
    '',
    'analytics.subscribe("checkout_started", async (e) => {',
    '  const c = e.data && e.data.checkout;',
    '  if (!sid) await ensureSession("", "");',
    '  send("checkout", { product: firstItem(c), value: num(c && c.totalPrice && c.totalPrice.amount) });',
    '});',
    '',
    'analytics.subscribe("checkout_completed", async (e) => {',
    '  const c = e.data && e.data.checkout;',
    '  if (!sid) await ensureSession("", "");',
    '  send("purchase", { product: firstItem(c), value: num(c && c.totalPrice && c.totalPrice.amount) });',
    '});',
    '',
  ].join('\n')
}
